name: CI

on:
  push:
    branches:
      - main # temporary until release process is in place
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: ".nvmrc"

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm run lint

      - name: prettier:check
        run: pnpm run prettier:check

      - name: test:unit
        run: pnpm run test:unit

      - name: build
        run: pnpm run build

  #      - name: run e2e tests
  #        run: pnpm run test:e2e
  #        env:
  #          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  #          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  #          SAUCE_REGION: eu

  release:
    needs: build
    #    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }} # TODO: enable this before merge
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup git for writing
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: ".nvmrc"

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Setup npm auth
        run: npm config set //npm.pkg.github.com/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run release-it
        run: pnpm run release
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Temporary release to private github packages npm only
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
